using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using System.Windows;
using System.Windows.Controls;
using System.Windows.Data;
using System.Windows.Documents;
using System.Windows.Input;
using System.Windows.Media;
using System.Windows.Media.Imaging;
using System.Windows.Navigation;
using System.Windows.Shapes;

namespace WpfApp2
{
    /// <summary>
    /// Логика взаимодействия для MainWindow.xaml
    /// </summary>
    public partial class MainWindow : Window
    {
        public MainWindow()
        {
            InitializeComponent();
        }

        int[] Mas = new int[15];

        private void Button_Click(object sender, RoutedEventArgs e)
        {
            textBox1.Clear();
            Random rand = new Random();
            for (int i = 0; i <= 14; i++)
            {
                Mas[i] = rand.Next(-50, 50);
                textBox1.Text += "Mas[" + i.ToString() + "] = " + Mas[i].ToString() + Environment.NewLine;

            }
        }

        private void Button_Click_1(object sender, RoutedEventArgs e)
        {
            textBox2.Clear();
            for (int i = 0; i <= 14; i++)
            {
                if (Mas[i] < 0)
                    textBox2.Text += "Mas[" + i.ToString() + "] - " + "отрицательное число" + Environment.NewLine;
                else
                    textBox2.Text += "Mas[" + i.ToString() + "] = " + Mas[i].ToString() + Environment.NewLine;
            }
        }
    }
}
